### ISSUE TITLE
requestUpdate has no effect

### ISSUE THREAD

**Issue by gronke** [morbidick/lit-element-notify#11]
After manually calling `this.requestUpdate("myproperty")`, the parent is not notified.

This snippet to remove an index from the `myproperty` Array properly propagates changes within one element, but not to the parent.

```
this.myproperty.slice(index, 1)
this.requestUpdate("myproperty");
```

Spread and Array.slice can be used as workaround:

```
this.myproperty = [
	...myproperty.slice(0, index),
	...myproperty.slice(index + 1)
];
```

see https://stackoverflow.com/questions/47023975/what-is-the-cleanest-way-to-remove-an-element-from-an-immutable-array-in-js/47024021#47024021

**Comment by morbidick** [comment]
interesting catch, the `update` method is used to detect property changes, i'll have a look at the lit-element source how `requestUpdate` gets handled internally

**Comment by morbidick** [comment]
After digging into it, it works as expected. Lit-element is only doing a [shallow ckeck](https://lit-element.polymer-project.org/guide/properties#haschanged] if the property has changed, since the object is still the same and only its content changed no render is triggered. We could preemptively call equestUpdate` in the `sync` method every time but that doesnt solve the problem when passing the object to a child.
So I would prefer to keep it consistent.
